services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: src/CB.Api/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=myappdb;Username=myuser;Password=mypassword
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"

  worker:
    build:
      context: .
      dockerfile: src/CB.Bot/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=myappdb;Username=myuser;Password=mypassword
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata:
