// <auto-generated />
using System;
using CB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CB.Data.Migrations
{
    [DbContext(typeof(CbContext))]
    [Migration("20250710220537_AddConfigsAndChannel")]
    partial class AddConfigsAndChannel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CB.Data.Entities.AllowConfiguration", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("text");

                    b.Property<bool>("AllowCrosspost")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowDiscordLive")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowFfa")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowGoodbyes")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowGreetings")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowLive")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowLiveDiscovery")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowPublished")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowStreamVod")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowThumbnails")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("AllowConfiguration");
                });

            modelBuilder.Entity("CB.Data.Entities.Channel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("CB.Data.Entities.ChannelConfiguration", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<string>("DiscordLiveChannelId")
                        .HasColumnType("text");

                    b.Property<string>("GoodbyeChannelId")
                        .HasColumnType("text");

                    b.Property<string>("GreetingChannelId")
                        .HasColumnType("text");

                    b.Property<string>("LiveChannelId")
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("DiscordLiveChannelId");

                    b.HasIndex("GoodbyeChannelId");

                    b.HasIndex("GreetingChannelId");

                    b.HasIndex("LiveChannelId");

                    b.ToTable("ChannelConfigurations", (string)null);
                });

            modelBuilder.Entity("CB.Data.Entities.Creator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Creators", (string)null);
                });

            modelBuilder.Entity("CB.Data.Entities.Guild", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Guilds", (string)null);
                });

            modelBuilder.Entity("CB.Data.Entities.GuildConfiguration", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("text");

                    b.Property<bool>("DeleteOffline")
                        .HasColumnType("boolean");

                    b.Property<bool>("TextAnnouncements")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigurations", (string)null);
                });

            modelBuilder.Entity("CB.Data.Entities.MessageConfiguration", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("text");

                    b.Property<string>("GoodbyeMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GreetingMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LiveMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublishedMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamOfflineMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("MessageConfigurations", (string)null);
                });

            modelBuilder.Entity("CB.Data.Entities.RoleConfiguration", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("text");

                    b.Property<string>("DiscoveryRoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JoinRoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LiveDiscoveryRoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("RoleConfigurations", (string)null);
                });

            modelBuilder.Entity("CB.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CB.Data.Entities.AllowConfiguration", b =>
                {
                    b.HasOne("CB.Data.Entities.Guild", "Guild")
                        .WithOne("AllowConfiguration")
                        .HasForeignKey("CB.Data.Entities.AllowConfiguration", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("CB.Data.Entities.Channel", b =>
                {
                    b.HasOne("CB.Data.Entities.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("CB.Data.Entities.ChannelConfiguration", b =>
                {
                    b.HasOne("CB.Data.Entities.Channel", null)
                        .WithMany("ChannelConfigurations")
                        .HasForeignKey("ChannelId");

                    b.HasOne("CB.Data.Entities.Channel", "DiscordLiveChannel")
                        .WithMany()
                        .HasForeignKey("DiscordLiveChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CB.Data.Entities.Channel", "GoodbyeChannel")
                        .WithMany()
                        .HasForeignKey("GoodbyeChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CB.Data.Entities.Channel", "GreetingChannel")
                        .WithMany()
                        .HasForeignKey("GreetingChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CB.Data.Entities.Guild", "Guild")
                        .WithOne("ChannelConfiguration")
                        .HasForeignKey("CB.Data.Entities.ChannelConfiguration", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CB.Data.Entities.Channel", "LiveChannel")
                        .WithMany()
                        .HasForeignKey("LiveChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiscordLiveChannel");

                    b.Navigation("GoodbyeChannel");

                    b.Navigation("GreetingChannel");

                    b.Navigation("Guild");

                    b.Navigation("LiveChannel");
                });

            modelBuilder.Entity("CB.Data.Entities.Creator", b =>
                {
                    b.HasOne("CB.Data.Entities.User", "User")
                        .WithMany("Creators")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CB.Data.Entities.Guild", b =>
                {
                    b.HasOne("CB.Data.Entities.User", "User")
                        .WithMany("Guilds")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CB.Data.Entities.GuildConfiguration", b =>
                {
                    b.HasOne("CB.Data.Entities.Guild", "Guild")
                        .WithOne("GuildConfiguration")
                        .HasForeignKey("CB.Data.Entities.GuildConfiguration", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("CB.Data.Entities.MessageConfiguration", b =>
                {
                    b.HasOne("CB.Data.Entities.Guild", "Guild")
                        .WithOne("MessageConfiguration")
                        .HasForeignKey("CB.Data.Entities.MessageConfiguration", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("CB.Data.Entities.RoleConfiguration", b =>
                {
                    b.HasOne("CB.Data.Entities.Guild", "Guild")
                        .WithOne("RoleConfiguration")
                        .HasForeignKey("CB.Data.Entities.RoleConfiguration", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("CB.Data.Entities.Channel", b =>
                {
                    b.Navigation("ChannelConfigurations");
                });

            modelBuilder.Entity("CB.Data.Entities.Guild", b =>
                {
                    b.Navigation("AllowConfiguration")
                        .IsRequired();

                    b.Navigation("ChannelConfiguration")
                        .IsRequired();

                    b.Navigation("Channels");

                    b.Navigation("GuildConfiguration")
                        .IsRequired();

                    b.Navigation("MessageConfiguration")
                        .IsRequired();

                    b.Navigation("RoleConfiguration")
                        .IsRequired();
                });

            modelBuilder.Entity("CB.Data.Entities.User", b =>
                {
                    b.Navigation("Creators");

                    b.Navigation("Guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
