CREATE TABLE [Discord].[Server]
(
	[Id] NUMERIC(20) NOT NULL PRIMARY KEY,
	[Name] nvarchar(128) NOT NULL,
	[OwnerId] NUMERIC(20) NOT NULL,
	[OwnerName] nvarchar(128) NOT NULL,
	[AnnouncementsChannel] NUMERIC(20) NULL,
	[GoLiveChannel] NUMERIC(20) NULL,
	[GreetingsChannel] NUMERIC(20) NULL,
	[OwnerLiveChannel] NUMERIC(20) NULL,
	[OwnerPublishedChannel] NUMERIC(20) NULL,
	[PublishedChannel] NUMERIC(20) NULL,
	[AllowEveryone] BIT NOT NULL,
	[AllowThumbnails] BIT NOT NULL,
	[AllowGreetings] BIT NOT NULL,
	[AllowGoodbyes] BIT NOT NULL,
	[AllowPublished] BIT NOT NULL,
	[AllowLive] BIT NOT NULL,
	[GreetingMessage] NVARCHAR(512) NULL,
	[GoodbyeMessage] NVARCHAR(512) NULL,
	[PublishedMessage] NVARCHAR(512) NULL,
	[LiveMessage] NVARCHAR(512) NULL,
	[TimeZoneOffset] INT NOT NULL DEFAULT (0),
	[YtgDomainPublished] BIT NOT NULL,
	[UseTextAnnouncements] BIT NOT NULL,
	[DeleteWhenOffline] BIT NOT NULL,
	[MentionRole] NUMERIC(20) NULL,
	[OwnerVidMeChannel] NUMERIC(20) NULL,
	[OwnerTwitchFeedChannel] NUMERIC(20) NULL,
	[TwitchFeedChannel] NUMERIC(20) NULL,
	[AllowChannelFeed] BIT NOT NULL,
	[AllowOwnerChannelFeed] BIT NOT NULL,
	[StreamOfflineMessage] NVARCHAR(512) NULL
)
